version: "3.8"
services:
  inceptia-challenge-dev:
    image: inceptia-challenge:dev
    container_name: development
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: [ "npm", "run", "dev" ]
    volumes:
      - ./src:/app/src
      - /app/node_modules
    ports:
      - "5173:5173"
